[package]
name = "scrap-dictionary"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.149"
axum = "0.8.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = "0.3.22"
